<a href="https://colab.research.google.com/github/techcoderR/python-/blob/master/Practice__Data_science_using_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NUMPY Practice

In [1]:
#importing Numpy library
import numpy as np

import sys


In [ ]:
a=np.array([1,2,3,4,5,4])
#implement multi indexing of array element using numpy 
a[[2,0,-1]]

array([3, 1, 4])

### Slicing

In [ ]:
#slicing
#1
a[1:]


array([2, 3, 4, 5, 4])

In [ ]:
#2
a[1::2] # jump method using arrya indexing


array([2, 4, 4])

In [ ]:
#3
a[::2]

array([1, 3, 5])

## Array type


In [ ]:
a.dtype

dtype('int64')

### Type Conversion

In [ ]:
np.array(a,dtype=np.float64)


array([1., 2., 3., 4., 5., 4.])

In [ ]:
np.array(a,dtype=np.int8)

array([1, 2, 3, 4, 5, 4], dtype=int8)

In [ ]:
np.array(a,dtype=np.int64)

array([1, 2, 3, 4, 5, 4])

### Matrics


In [ ]:
B=np.array([
            [
           [1,2,3,4],[2,3,45,5],
            ],
            [
             [1,2,3,4],[12,3,23,4]
            ]
])


In [ ]:
B.ndim

3

In [ ]:
B.dtype

dtype('int64')

In [ ]:
B.shape

(2, 2, 4)

In [ ]:
## inconsitenty in array size


A=np.array([
            [
           [1,2,3,4],[2,3,45,5],
            ],
            [
             [1,2,3,4],[12,3,23,23,4]
            ]
])


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  if __name__ == '__main__':


In [ ]:
A.ndim #this only show that array is 2 dimension

2

In [ ]:
A.shape #this only show 2 shape only this due to array is not fix size

(2, 2)

In [ ]:
A.dtype #the type of array is object now because it length and size of array is mixed called mixed matrices

dtype('O')

### Index and Slicing in Matrice

In [ ]:
A=np.array([
            
           [1,2,3,4],
          [2,3,45,5],
           [1,2,3,5]
            
])

In [ ]:
A[1]

array([ 2,  3, 45,  5])

In [ ]:
A[0:2]

array([[ 1,  2,  3,  4],
       [ 2,  3, 45,  5]])

In [ ]:
A[:2]

array([[ 1,  2,  3,  4],
       [ 2,  3, 45,  5]])

In [ ]:
A[:1]

array([[1, 2, 3, 4]])

In [ ]:
A[:3]

array([[ 1,  2,  3,  4],
       [ 2,  3, 45,  5],
       [ 1,  2,  3,  5]])

In [ ]:
# selecting all row but limit range of column
A[:,:2]

array([[1, 2],
       [2, 3],
       [1, 2]])

In [ ]:
#selecting only particular column in each row
A[:,2]

array([ 3, 45,  3])

In [ ]:
#replacement

A[1]=np.array([1,2,3,6])

In [ ]:
A

array([[1, 2, 3, 4],
       [1, 2, 3, 6],
       [1, 2, 3, 5]])

In [ ]:
A.sum()

33

In [ ]:
A.mean()

2.75

### vectorization of Matrics 

In [ ]:
a=np.arange(5)

#array doesnt save value which make change in it it always remain constant whether multiple operation will perform

In [ ]:
a

array([0, 1, 2, 3, 4])

In [ ]:
a+20

array([20, 21, 22, 23, 24])

In [ ]:

a*10

array([ 0, 10, 20, 30])

In [ ]:
b=np.array([10,10,10,20])
c=[29,29,38,29]

In [ ]:
a+b+c

array([39, 40, 50, 52])

In [ ]:
a=[1,2,3]
b=[2,3,4]


In [ ]:
a+b

[1, 2, 3, 2, 3, 4]

### Boolean Array

In [ ]:
a=np.array([1,2,3,4,5])

print(a[[0,-1]])   #print the element by selecting particular set parameter
print(a[a>=3])  #print the raw element by implement the condition into the array

[1 5]
[3 4 5]


In [ ]:
print(a>=3)  #implement a boolean array to filter the data by implement the condition

[False False  True  True  True]


In [ ]:
a.mean()

3.0

In [ ]:
a>=a.mean()  # implement mean condition on the array and find the boolean data

array([False, False,  True,  True,  True])

In [ ]:
a[a>=a.mean()] #print the element inside the mean


array([3, 4, 5])

In [ ]:
a[(a==0)|(a>=3)]

array([3, 4, 5])

In [ ]:
a[(a<=5)&(a>=0)]

array([1, 2, 3, 4, 5])

##### use random function

In [ ]:
a=np.random.randint(100,size=[4,3]) #implement the random 4X3 matrics

In [ ]:
a 

array([[65, 23, 76],
       [28, 22, 60],
       [71, 38, 71],
       [73,  6, 98]])

In [ ]:
a>50    #apply the condition for getting the boolean array

array([[ True, False,  True],
       [False, False,  True],
       [ True, False,  True],
       [ True, False,  True]])

In [ ]:
a[a>50]  # print the array element 

array([65, 76, 60, 71, 71, 73, 98])

### Linear Algebra

In [ ]:
a=np.random.randint(100,size=[4,3])

In [ ]:
b=np.random.randint(100,size=[3,4])

In [ ]:
a.dot(b) #dot product of matrics

array([[ 6841, 12057,  6390,  6580],
       [ 6954,  7910,  8008,  1676],
       [ 6379, 10241,  6178,  5877],
       [ 5618,  7732,  5738,  4740]])

In [ ]:
a@(b)  #cross product of matrics

array([[ 6841, 12057,  6390,  6580],
       [ 6954,  7910,  8008,  1676],
       [ 6379, 10241,  6178,  5877],
       [ 5618,  7732,  5738,  4740]])

In [ ]:
b.T #transpose product

array([[60, 53, 20],
       [33, 98, 57],
       [75, 55,  9],
       [18,  7, 59]])

In [ ]:
a.T

array([[32, 64, 41, 50],
       [57, 58, 43, 26],
       [95,  2, 82, 62]])

In [ ]:
a.dot(b)

array([[ 6841, 12057,  6390,  6580],
       [ 6954,  7910,  8008,  1676],
       [ 6379, 10241,  6178,  5877],
       [ 5618,  7732,  5738,  4740]])

### Size of object in memory

In [ ]:
sys.getsizeof(1) #integer value memory in python

28

In [ ]:
sys.getsizeof(1.9000) #float value memory in python

24

In [ ]:
sys.getsizeof("A") #char value memory in python

50

In [ ]:
sys.getsizeof([]) #list memory value in python

80

In [ ]:
np.dtype(np.int8).itemsize  #integer value of int 8bit  in numpy

1

In [ ]:
np.dtype(int).itemsize  #integer value in numpy

8

In [ ]:
np.dtype(float).itemsize #float value in numpy 

8

### Speed Comparison Python vs Numpy

In [ ]:
l=list(range(1000))
a=np.arange(1000)

In [ ]:
%time np.sum(a**2)

CPU times: user 123 µs, sys: 0 ns, total: 123 µs
Wall time: 128 µs


332833500

In [ ]:
%time sum([x**2 for x in l])

CPU times: user 582 µs, sys: 0 ns, total: 582 µs
Wall time: 588 µs


332833500

### NUmpy Function

#### random

In [ ]:
np.random.random(size=2)

array([0.13250475, 0.68862702])

In [ ]:
np.random.normal(size=8)

array([-1.51893796, -0.54874702,  0.95039233, -1.31817672, -0.82990675,
       -0.15936111, -0.47661344, -0.3934322 ])

In [ ]:
np.random.rand(3,3)

array([[0.02414581, 0.66997333, 0.02522431],
       [0.71603166, 0.609703  , 0.92981996],
       [0.11233208, 0.98813667, 0.16469842]])

#### Arange

In [ ]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(5,10,2) #using jump in array (startindex,endindex,jump size)

array([5, 7, 9])

In [ ]:
np.arange(10,3,-2) #reverse jump array (endindex,startindex,negative jump size)

array([10,  8,  6,  4])

#### reshape

In [ ]:
np.arange(10).reshape(2,5) #reshape function to make array by user define method

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
np.arange(10).reshape(5,2)  #reshape function to make array by user define method

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

###linspace

In [ ]:
np.linspace(10,100,5) #divide the given particular range into number of divide given(start ,end,number of divide for given range)

array([ 10. ,  32.5,  55. ,  77.5, 100. ])

In [ ]:
np.linspace(0,1,5,True) #it divide into 5 part

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.linspace(0,1,5,False) #it separate it by 2 into 5 part also not equal to the given end limit


array([0. , 0.2, 0.4, 0.6, 0.8])

#### Zeros ,ones,Empty

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.empty((2,2))

array([[0.2, 0.4],
       [0.6, 0.8]])

#### Identity and Eye

In [ ]:
np.identity(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.eye(4, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.eye(8, 4, k=-3) #shift the diagonal by -3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [ ]:
np.eye(8, 4, k=2) #shift the diagonal by 2 upward

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### String manipulation

In [ ]:
"Hello World"[2:8]

'llo Wo'

In [ ]:
"Hello World"[2:]

'llo World'

In [ ]:
"Hello World"[1::2]

'el ol'

#Pandas Practice


####Pandas Series

In [2]:
import pandas as pd


In [3]:
# In millions
g7_pop = pd.Series([35.467, 63.951, 80.940, 60.665, 127.061, 64.511, 318.523])

In [4]:
g7_pop

0     35.467
1     63.951
2     80.940
3     60.665
4    127.061
5     64.511
6    318.523
dtype: float64

In [5]:
g7_pop.name = 'G7 Population in millions'

In [6]:
g7_pop.values # retrive the value of the series

array([ 35.467,  63.951,  80.94 ,  60.665, 127.061,  64.511, 318.523])

In [7]:
g7_pop[0]

35.467

In [8]:
g7_pop[1]

63.951

In [9]:
g7_pop.index

RangeIndex(start=0, stop=7, step=1)

In [11]:
g7_pop.index = [
    'Canada',
    'France',
    'Germany',
    'Italy',
    'Japan',
    'United Kingdom',
    'United States',
]   ### defining the index in series to get the data of population

In [12]:
g7_pop

Canada             35.467
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
Name: G7 Population in millions, dtype: float64

#### You can also create Series out of other series, specifying indexes:

In [13]:
pd.Series(
    [35.467, 63.951, 80.94, 60.665, 127.061, 64.511, 318.523],
    index=['Canada', 'France', 'Germany', 'Italy', 'Japan', 'United Kingdom',
       'United States'],
    name='G7 Population in millions')

Canada             35.467
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
Name: G7 Population in millions, dtype: float64

#####  We can say that Series look like "ordered dictionaries". We can actually create Series out of dictionaries:

In [14]:
pd.Series({
    'Canada': 35.467,
    'France': 63.951,
    'Germany': 80.94,
    'Italy': 60.665,
    'Japan': 127.061,
    'United Kingdom': 64.511,
    'United States': 318.523
}, name='G7 Population in millions')

Canada             35.467
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
Name: G7 Population in millions, dtype: float64

In [15]:
pd.Series(g7_pop, index=['France', 'Germany', 'Italy', 'Spain'])

France     63.951
Germany    80.940
Italy      60.665
Spain         NaN
Name: G7 Population in millions, dtype: float64

## Indexing

In [16]:
g7_pop['Canada']

35.467

In [18]:
g7_pop['Germany'] ## case sensative [germany will give error]

80.94

##### Numeric positions can also be used, with the iloc attribute:

In [19]:
g7_pop.iloc[0]

35.467

In [20]:
g7_pop.iloc[-1]

318.523

In [21]:
g7_pop.iloc[[0, 1]]

Canada    35.467
France    63.951
Name: G7 Population in millions, dtype: float64

#### Conditional selection (boolean arrays)

In [22]:
g7_pop > 70 ## implement the boolean check 


Canada            False
France            False
Germany            True
Italy             False
Japan              True
United Kingdom    False
United States      True
Name: G7 Population in millions, dtype: bool

In [23]:
g7_pop[g7_pop>70] ## the output with condition 

Germany           80.940
Japan            127.061
United States    318.523
Name: G7 Population in millions, dtype: float64

In [24]:
g7_pop[g7_pop>g7_pop.mean()]

Japan            127.061
United States    318.523
Name: G7 Population in millions, dtype: float64

In [25]:
g7_pop[(g7_pop > g7_pop.mean() - g7_pop.std() / 2) | (g7_pop > g7_pop.mean() + g7_pop.std() / 2)]

France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
Name: G7 Population in millions, dtype: float64

In [27]:
g7_pop.std() ####The Pandas std() is defined as a function for calculating the standard deviation of the given set of numbers, DataFrame, column, and rows. 

97.24996987121581

#### Operations and methods

In [30]:
g7_pop*1000000

Canada             35467000.0
France             63951000.0
Germany            80940000.0
Italy              60665000.0
Japan             127061000.0
United Kingdom     64511000.0
United States     318523000.0
Name: G7 Population in millions, dtype: float64

In [31]:
g7_pop.mean()

107.30257142857144

In [32]:
g7_pop['France': 'Italy'].mean()

68.51866666666666

#### Boolean arrays

In [33]:
g7_pop[(g7_pop > 80) | (g7_pop < 40)]

Canada            35.467
Germany           80.940
Japan            127.061
United States    318.523
Name: G7 Population in millions, dtype: float64

In [34]:
g7_pop[g7_pop > 80]

Germany           80.940
Japan            127.061
United States    318.523
Name: G7 Population in millions, dtype: float64

In [35]:
g7_pop[(g7_pop > 80) & (g7_pop < 200)]

Germany     80.940
Japan      127.061
Name: G7 Population in millions, dtype: float64

#### Modifiying Series

In [37]:
g7_pop['Canada'] = 40.5

In [38]:
g7_pop

Canada             40.500
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
Name: G7 Population in millions, dtype: float64

In [39]:
g7_pop.iloc[-1] = 500

In [40]:
g7_pop

Canada             40.500
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     500.000
Name: G7 Population in millions, dtype: float64